version: '3'

services:
  backend:
    build: .
    ports:
      - 8080:8080
    restart: always
    networks:
      - spring-postgres
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:alpine
    ports:
      - "6043:5432"
    environment:
      POSTGRES_PASSWORD: "dataweaver"
      POSTGRES_DB: "dataweaver"
    networks:
      - spring-postgres
networks:
  spring-postgres:
    driver: bridge